# Generated by Django 3.1.2 on 2020-11-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20201107_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
