# Generated by Django 3.1.2 on 2020-11-16 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='submitted_by',
        ),
    ]
