# Generated by Django 3.1.2 on 2020-11-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_project_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloudinary_screenshot_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
