# Generated by Django 3.1.2 on 2020-10-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100)),
                ('link', models.URLField()),
                ('maker_fullname', models.CharField(max_length=100)),
                ('twitter_handle', models.CharField(max_length=20)),
                ('github_handle', models.CharField(max_length=20)),
                ('producthunt_handle', models.CharField(max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('link', 'maker_fullname')},
            },
        ),
    ]
