# Generated by Django 3.1.2 on 2020-11-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=100)),
                ('link', models.URLField()),
                ('maker_fullname', models.CharField(max_length=100)),
                ('twitter_handle', models.CharField(max_length=20, null=True)),
                ('github_handle', models.CharField(max_length=20, null=True)),
                ('producthunt_handle', models.CharField(max_length=20, null=True)),
                ('is_approved', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('link', 'maker_fullname')},
            },
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvoted_project', to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='project.project')),
            ],
        ),
    ]
