# Generated by Django 3.1.2 on 2020-10-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
