# Generated by Django 3.1.2 on 2020-11-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20201105_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated strings', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
