# Generated by Django 3.1.2 on 2020-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='avatar',
        ),
        migrations.AddField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, default='screenshot/default.png', null=True, upload_to='screenshot/'),
        ),
    ]
