# Generated by Django 3.1.2 on 2020-11-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20201109_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshot/'),
        ),
    ]
