# Generated by Django 3.1.2 on 2020-11-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='maker_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
