# Generated by Django 3.1.2 on 2020-11-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_project_cloudinary_screenshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cloudinary_maker_avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
