# Generated by Django 3.1.2 on 2020-12-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_project_cloudinary_maker_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_handle',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='producthunt_handle',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
