# Generated by Django 3.1.2 on 2020-12-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20201204_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='twitter_followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
