# Generated by Django 3.1.2 on 2021-03-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_project_twitter_followers_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='producthunt_handle',
        ),
    ]
