# Generated by Django 3.1.2 on 2021-03-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_project_producthunt_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='maker_bio',
        ),
    ]
