# Generated by Django 4.0.3 on 2022-04-03 02:25

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_remove_project_maker_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='maker_avatar',
            field=models.ImageField(blank=True, null=True, storage=project.models.OverwriteStorage, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, storage=project.models.OverwriteStorage, upload_to='screenshot/'),
        ),
    ]
